{{- $root := . -}}
{{- $driver := .Values.drivers.cephfs -}}
{{- if $driver.enabled }}
{{- $normalizedDriverName := include "normalizeDriverName" $driver.name }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $normalizedDriverName }}-nodeplugin-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $normalizedDriverName }}-nodeplugin-r
subjects:
- kind: ServiceAccount
  name: {{ $normalizedDriverName }}-nodeplugin-sa
  namespace: {{ $root.Release.Namespace }}
{{- end }}
