kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-rbd-ctrlplugin-rb
subjects:
  - kind: ServiceAccount
    name: csi-rbd-ctrlplugin-sa
    namespace: system
roleRef:
  kind: Role
  name: csi-rbd-ctrlplugin-r
  apiGroup: rbac.authorization.k8s.io
