{{- $root := . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ceph-csi-operator.fullname" . }}-cephfs-nodeplugin-rb
  namespace: {{ $root.Release.Namespace }}
  labels:
  {{- include "ceph-csi-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "ceph-csi-operator.fullname" . }}-cephfs-nodeplugin-r'
subjects:
- kind: ServiceAccount
  name: '{{ include "ceph-csi-operator.fullname" . }}-cephfs-nodeplugin-sa'
  namespace: '{{ .Release.Namespace }}'
