## Append samples of your project ##
resources:
- csi_v1alpha1_driver.yaml
- csi_v1alpha1_operatorconfig.yaml
- csi_v1alpha1_cephconnection.yaml
- csi_v1alpha1_clientprofile.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
